// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TestProto.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetByNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Requester            string   `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByNameRequest) Reset()         { *m = GetByNameRequest{} }
func (m *GetByNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetByNameRequest) ProtoMessage()    {}
func (*GetByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40bd3d5700522baa, []int{0}
}

func (m *GetByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByNameRequest.Unmarshal(m, b)
}
func (m *GetByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByNameRequest.Marshal(b, m, deterministic)
}
func (m *GetByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByNameRequest.Merge(m, src)
}
func (m *GetByNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetByNameRequest.Size(m)
}
func (m *GetByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByNameRequest proto.InternalMessageInfo

func (m *GetByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetByNameRequest) GetRequester() string {
	if m != nil {
		return m.Requester
	}
	return ""
}

type GetResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40bd3d5700522baa, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SetByNameRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetByNameRequest) Reset()         { *m = SetByNameRequest{} }
func (m *SetByNameRequest) String() string { return proto.CompactTextString(m) }
func (*SetByNameRequest) ProtoMessage()    {}
func (*SetByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40bd3d5700522baa, []int{2}
}

func (m *SetByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetByNameRequest.Unmarshal(m, b)
}
func (m *SetByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetByNameRequest.Marshal(b, m, deterministic)
}
func (m *SetByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetByNameRequest.Merge(m, src)
}
func (m *SetByNameRequest) XXX_Size() int {
	return xxx_messageInfo_SetByNameRequest.Size(m)
}
func (m *SetByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetByNameRequest proto.InternalMessageInfo

type SetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40bd3d5700522baa, []int{3}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

type DeleteByNameRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByNameRequest) Reset()         { *m = DeleteByNameRequest{} }
func (m *DeleteByNameRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteByNameRequest) ProtoMessage()    {}
func (*DeleteByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40bd3d5700522baa, []int{4}
}

func (m *DeleteByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByNameRequest.Unmarshal(m, b)
}
func (m *DeleteByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByNameRequest.Marshal(b, m, deterministic)
}
func (m *DeleteByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByNameRequest.Merge(m, src)
}
func (m *DeleteByNameRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteByNameRequest.Size(m)
}
func (m *DeleteByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByNameRequest proto.InternalMessageInfo

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40bd3d5700522baa, []int{5}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetByNameRequest)(nil), "proto.GetByNameRequest")
	proto.RegisterType((*GetResponse)(nil), "proto.GetResponse")
	proto.RegisterType((*SetByNameRequest)(nil), "proto.SetByNameRequest")
	proto.RegisterType((*SetResponse)(nil), "proto.SetResponse")
	proto.RegisterType((*DeleteByNameRequest)(nil), "proto.DeleteByNameRequest")
	proto.RegisterType((*DeleteResponse)(nil), "proto.DeleteResponse")
}

func init() { proto.RegisterFile("TestProto.proto", fileDescriptor_40bd3d5700522baa) }

var fileDescriptor_40bd3d5700522baa = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x53, 0x8b, 0x24, 0x0c, 0xfe, 0xa9, 0x63, 0x88, 0x4d, 0xe3, 0x81, 0xec, 0x89, 0x13,
	0x87, 0x7a, 0xf4, 0xa6, 0x24, 0x8d, 0x17, 0x63, 0xba, 0x7e, 0x81, 0x55, 0xde, 0x81, 0x04, 0xda,
	0xba, 0x3b, 0x9a, 0xf0, 0xcd, 0xfc, 0x78, 0x86, 0x5d, 0xb0, 0x40, 0xca, 0xa5, 0x7d, 0x79, 0xbf,
	0x79, 0x93, 0x37, 0x4b, 0xd7, 0xef, 0x70, 0xf2, 0x66, 0x6b, 0xa9, 0xa7, 0xcd, 0xe6, 0xcb, 0xe7,
	0xfe, 0xa7, 0x66, 0x94, 0x14, 0x90, 0xa7, 0xf5, 0xab, 0x59, 0xa1, 0xc4, 0xd7, 0x37, 0x9c, 0x30,
	0x53, 0xaf, 0x32, 0x2b, 0xa4, 0xd1, 0x38, 0x9a, 0x0c, 0x4a, 0xaf, 0xf9, 0x9e, 0x06, 0x36, 0x60,
	0xd8, 0xf4, 0xcc, 0x83, 0xd6, 0x50, 0x2f, 0x34, 0x2c, 0x20, 0x25, 0x5c, 0x53, 0x57, 0x0e, 0x9d,
	0x0b, 0x98, 0x7a, 0xb2, 0x6e, 0xb0, 0xcd, 0x7a, 0xbd, 0xf1, 0xe6, 0x46, 0x4c, 0x1a, 0x8f, 0xa3,
	0xc9, 0x45, 0xe9, 0xb5, 0x62, 0x4a, 0xf4, 0x51, 0x21, 0x75, 0x49, 0x43, 0xdd, 0xae, 0x57, 0x23,
	0xba, 0x9d, 0x61, 0x09, 0xc1, 0xe1, 0x54, 0x42, 0x57, 0xc1, 0xde, 0x0d, 0xe6, 0xbf, 0x11, 0xdd,
	0x3c, 0x5b, 0xcc, 0x51, 0xc9, 0xc2, 0x2c, 0x35, 0xec, 0xcf, 0xe2, 0x13, 0x9c, 0x53, 0x5c, 0x40,
	0xf8, 0x2e, 0x3c, 0xc4, 0xf4, 0xf8, 0xfc, 0x8c, 0x5b, 0xf0, 0x7f, 0x51, 0x4e, 0xb1, 0xde, 0xcb,
	0xe8, 0x53, 0x99, 0xbd, 0x9a, 0xfc, 0x48, 0xfd, 0xd0, 0x87, 0xb3, 0x2d, 0xed, 0x68, 0x9d, 0x8d,
	0x0e, 0xd8, 0x2e, 0xfc, 0xd1, 0xf7, 0xee, 0xc3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x59,
	0x5f, 0x86, 0xb8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CredentialServiceClient is the client API for CredentialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CredentialServiceClient interface {
	Get(ctx context.Context, in *GetByNameRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetByNameRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Delete(ctx context.Context, in *DeleteByNameRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type credentialServiceClient struct {
	cc *grpc.ClientConn
}

func NewCredentialServiceClient(cc *grpc.ClientConn) CredentialServiceClient {
	return &credentialServiceClient{cc}
}

func (c *credentialServiceClient) Get(ctx context.Context, in *GetByNameRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/proto.CredentialService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialServiceClient) Set(ctx context.Context, in *SetByNameRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/proto.CredentialService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialServiceClient) Delete(ctx context.Context, in *DeleteByNameRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/proto.CredentialService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialServiceServer is the server API for CredentialService service.
type CredentialServiceServer interface {
	Get(context.Context, *GetByNameRequest) (*GetResponse, error)
	Set(context.Context, *SetByNameRequest) (*SetResponse, error)
	Delete(context.Context, *DeleteByNameRequest) (*DeleteResponse, error)
}

func RegisterCredentialServiceServer(s *grpc.Server, srv CredentialServiceServer) {
	s.RegisterService(&_CredentialService_serviceDesc, srv)
}

func _CredentialService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CredentialService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).Get(ctx, req.(*GetByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CredentialService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).Set(ctx, req.(*SetByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CredentialService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).Delete(ctx, req.(*DeleteByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CredentialService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CredentialService",
	HandlerType: (*CredentialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CredentialService_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _CredentialService_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CredentialService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TestProto.proto",
}
